saratings/saratings/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path, include
from django_otp.admin import OTPAdminSite
import os

admin.site.site_header = "SA Ratings Administration"

#Enfore 2FA in all environments
# if 'aws' in os.uname()[2]:
#     admin.site.__class__ = OTPAdminSite


urlpatterns = [
    path('sar-adm/', admin.site.urls),
    path("", include("saratingsapp.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(
                          template_name='registration/password_reset_submit.html'),
                            name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_submitted.html'),
	    name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
                    template_name='registration/password_reset_confirmation.html'),
	                name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_completed.html'),
	name='password_reset_complete'),
]

#Append 'MEDIA_URL' and 'MEDIA_ROOT' to urlpatterns
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

saratings/saratingsapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from saratingsapp.views import *
from django.conf import settings

"""
New URLS added in Dev
Added new views in Dev for report purchase and subscription:
ie research_reports_subscription_list 
"""

urlpatterns = [
    path("register/", registration, name="register"),
    path("login/", user_login, name="login"),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path("logout/", user_logout, name="logout"),
    path("", sar_home, name="sar_home"),
    path("about/", sar_about, name="sar_about"),
    path("mission-vision/", sar_mission, name="sar_mission"),
    path("team/", sar_team, name="sar_team"),
    # path("contact/", sar_contact, name="sar_contact"),
    path('events/',event_homepage, name="eventsHomepage"),
    path('event-rsvp/<str:event_id>',event_rsvp, name="eventRSVP"),
    path('media-page/',media_homepage, name="mediaHomepage"),
    path('regulatory/public-commentary/articles',public_commentary_article_list, name="publicCommentaryArticleList"),
    path('regulatory/public-commentary/article/<str:unique_id>',view_commentary_article, name="viewCommentaryArticle"),
    path('regulatory/public-commentary/article/<str:unique_id>/comment',comment_commentary_article, name="commentCommentaryArticle"),
    path('ratings-publication/',ratings_publication_list, name="ratingsPublications"),
    path('ratings-methodology/',ratings_methodology_list, name="ratingsMethodologies"),
    path('research-reports/',resarch_publication_list, name="researchPublications"),
    path('list-economic-nuggets/',nuggets_publication_list, name="nuggets_publication_list"),
    path('read-economic-nugget/<str:unique_id>',read_nugget, name="read_nugget"),
    path('list-year-in-review/',year_in_review_publication_list, name="year_in_review_publication_list"),
    path('purchase-research/',purchase_research, name="purchase_research"),
    path('reports-subscriptions/',research_reports_subscription_list, name="reports_subscription_list"),
    path('sar-policies',sar_policy_list,name="SARPoliyList"),
    path('sector-commentary',sector_commentary_list,name="sectorCommentaryList"),
    path('issuer-commentary',issuer_commentary_list,name="issuerCommentaryList"),
    path('annual-reports',annual_reports_list,name="annualReportsList"),
    path('nugget-document-upload',nugget_document_upload,name="nuggetdocumentUpload"),
    path('not-authorised',user_not_authorised,name="userNotAuthorised"),      
    path('savedoctohtmlfile',save_docx_to_html_file,name="createDocxToHtmlFile"),
    
]

#Append 'MEDIA_URL' and 'MEDIA_ROOT' to urlpatterns for PROD
# if IS_DEV:
#     urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saratings/saratingsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings
import asyncio,os,shutil, random, string
from pathlib import Path

if settings.IS_PROD:
    print("Running mails in PROD")
    base_url = 'https://saratings.com/read-weekly-economic-nugget/'
    year_in_review_base_url = 'https://saratings.com/read-year-in-review/'
    mailing_list = ["jason@saratings.com","jasonm@plus94.co.za","tumi@saratings.com","zweli@saratings.com","wayne@bettersa.co.za","liza@socialhat.co.za"]

else:
    print("Running mails in DEV")
    base_url = 'http://127.0.0.1:8001/read-weekly-economic-nugget/'
    year_in_review_base_url = 'http://127.0.0.1:8001/read-year-in-review/'
    mailing_list = ["jason@saratings.com","jasonm@plus94.co.za"]

from_email_address = settings.EMAIL_HOST_USER
BASE_DIR = Path(__file__).resolve().parent.parent
    

"""
For asyncio PROD
https://python.readthedocs.io/en/stable/library/asyncio-task.html
""" 
async def send_email(subject, message):   
    
    bcc_recipient_list = mailing_list
    """
    empty_recipient_list is for the 'to' field
    bcc_recipient_list is for the 'bcc' feld
    """
    empty_recipient_list = []
    email = EmailMessage(
    subject,
    message,
    from_email_address,
    empty_recipient_list,
    bcc_recipient_list,
    )  
            
    email.send(fail_silently=False)



def send_email_async(subject, message):
    
    bcc_recipient_list = mailing_list
    empty_recipient_list = []
    
    email = EmailMessage(
    subject,
    message,
    from_email_address,
    empty_recipient_list,
    bcc_recipient_list
    )  
         
    return email.send(fail_silently=False)
    

async def confirm_sent_notification():
    
    print("Email notification sent")

User._meta.get_field('email')._unique = True

#Generate a modal ref string
def get_string(letters_count, digits_count):
    
    letters = ''.join((random.choice(string.ascii_letters) for i in range(letters_count)))
    
    digits = ''.join((random.choice(string.digits) for i in range(digits_count)))

    # Convert resultant string to list and shuffle it to mix letters and digits
    sample_list = list(letters + digits)
    random.shuffle(sample_list)
    # convert list to string
    final_string = ''.join(sample_list)

    return final_string
    
class UserProfile(models.Model):
	
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    email = models.EmailField(max_length=60, unique=True,null=True,blank=False)
    first_name = models.CharField(max_length=30,null=True,blank=False)
    last_name = models.CharField(max_length=30,null=True,blank=False)
    cell_number = models.CharField(validators=[MinLengthValidator(10)],max_length=11, null=True,blank=False,unique=True)
    profile_ref = models.CharField(max_length=90, unique=True,null=True,blank=True)
    
    #Users are activated via a link sent to their email or sms
    is_user_activated = models.BooleanField(default=False,null=True,blank=True)
    has_subscribed = models.BooleanField(default=0)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        
        get_first_name = self.first_name
        get_last_name = self.last_name
        
        get_full_name = ""
        if get_first_name == None or get_last_name == None or get_first_name == "" or get_last_name == "":
            get_full_name = self.user.username
        if get_first_name != None and get_last_name != None:
            get_full_name = get_first_name + " " + get_last_name

        return get_full_name


    class Meta:
        db_table = "user_profile"
        ordering = ('user',)
        verbose_name_plural = 'User Profiles'
        
# Generate a modal ref string
def get_string(letters_count, digits_count):
    
    letters = ''.join((random.choice(string.ascii_letters) for i in range(letters_count)))
    
    digits = ''.join((random.choice(string.digits) for i in range(digits_count)))

    # Convert resultant string to list and shuffle it to mix letters and digits
    sample_list = list(letters + digits)
    random.shuffle(sample_list)
    # convert list to string
    final_string = ''.join(sample_list)

    return final_string

def doc_upload_location(instance, filename):
    
    return '{0}/{1}'.format(get_string(6,6), filename)


class FileUpload(models.Model):
    file_name = models.CharField(max_length=100, null=True, blank=True,unique=True)
    upload_file = models.FileField(upload_to=doc_upload_location, blank=True,null=True)
    uploaded_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    upload_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    
    def __str__(self):
        return self.file_name
    
    class Meta:
        db_table = "file_upload"

        
class LeadershipProfile(models.Model):
    
    name = models.CharField(max_length=100, null=True, blank=True)
    position = models.CharField(max_length=100, null=True, blank=True)
    profile_image = models.ImageField(upload_to='leadership/', null=True, blank=True)
    profile_bio = models.TextField(null=True, blank=True)
    profile_ref = models.CharField(max_length=90, unique=True,null=True,blank=True)
    is_non_executive = models.BooleanField(default=False,null=True,blank=True)
    is_executive = models.BooleanField(default=False,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    date_updated = models.DateTimeField(auto_now=True,null=True,blank=True)
    
    def __str__(self):
        return str(self.name)
    
    def save(self, *args, **kwargs):
        self.profile_ref = get_string(6,6)
        super(LeadershipProfile, self).save(*args, **kwargs)
        
    class Meta:
        db_table = "leadership_profile"
        
class SAREvent(models.Model):
    
    event_title = models.CharField(max_length=100, null=True, blank=True)
    event_id = models.CharField(max_length=100, null=True, blank=True,unique=True)
    event_date = models.DateField(null=True, blank=False)
    event_time = models.TimeField(null=True, blank=False)
    is_online = models.BooleanField(default=False,null=True,blank=True)
    meeting_recording_url = models.CharField(max_length=1000, null=True, blank=True)
    presentation_url = models.CharField(max_length=1000, null=True, blank=True) 
    event_presentation =  models.FileField(upload_to='presentations/', null=True, blank=True)
    is_in_person = models.BooleanField(default=False,null=True,blank=True)
    is_hybrid = models.BooleanField(default=False,null=True,blank=True)
    has_agenda = models.BooleanField(default=False,null=True,blank=True)
    rsvp_needed = models.BooleanField(default=False,null=True,blank=True)
    rsvp_link = models.CharField(max_length=1000, null=True, blank=True)
    event_venue = models.CharField(max_length=100, null=True, blank=True)
    introduction = models.TextField(null=True, blank=True)
    event_image =  models.ImageField(upload_to='events/', null=True, blank=True)
    agenda_item_1 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_2 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_3 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_4 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_5 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_6 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_7 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_8 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_9 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_10 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_11 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_12 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_13 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_14 = models.CharField(max_length=255, null=True, blank=True)
    agenda_item_15 = models.CharField(max_length=255, null=True, blank=True) 
    
    def __str__(self):
        return str(self.event_title)
    
    def save(self, *args,**kwards):
        if not self.event_id:
            self.event_id =str(get_string(20,20))
        super(SAREvent, self).save(*args,**kwards)
    
    class Meta:
        db_table = "sar_event"
        verbose_name_plural = "SAR Events"
        
     
class EventRSVP(models.Model):
    event = models.ForeignKey(SAREvent, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=False)
    first_name = models.CharField(max_length=100, null=True, blank=False)
    last_name = models.CharField(max_length=100, null=True, blank=False)
    company =  models.CharField(max_length=100, null=True, blank=False)
    email_address = models.EmailField(max_length=100, null=True, blank=False)
    contact_number = models.CharField(max_length=100, null=True, blank=False)
    rsvp_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    rsvp_updated = models.DateTimeField(auto_now=True,null=True,blank=True)
    confirm_attendance = models.CharField(max_length=20, null=True, blank=False)
    
    
    def __str__(self):
        return str(self.event)
    
    class Meta:
        db_table = "event_rsvp"
        verbose_name_plural = "Events RSVP"

class MediaPage(models.Model):
    
    file_name = models.CharField(max_length=100, null=True, blank=True,unique=True)
    file_description = models.TextField(null=True, blank=True)
    file_type = models.CharField(max_length=10, null=True, blank=True)
    file_link = models.TextField(null=True, blank=True)
    
    #Youtube, audio streaming

saratings/saratingsapp/templates/events/event_rsvp.html
{% load static %}
{%load crispy_forms_tags%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>SAR|Events</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/logo/sar_logo.svg'%}" style="width:10%!important" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">
  <link href="{% static 'assets/css/form.css'%}" rel="stylesheet">

</head>

<body>


  <style>

header#header{
      background: #212529!important;
    }

    #sar_title{
      font-weight: bold;
      
    }

    #news,#testimonials,#insights,#research,#social_media_links,#articles{
      display:none;
    }
   

    footer.col-md-12 {
      bottom: 0;
  }
 
  .footer-area {
    padding: 0;
  }

  label {
    color: #000000!important;
    font-size: 15px!important;
  }

  .help-block {
    color: #dc3545!important;
}

  </style>

  <!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <h1><a href="{%url 'sar_home'%}"><span style="font-size:1.6rem!important"><img src="{% static 'assets/img/logo/sar_logo.svg'%}" style="width:8%!important;vertical-align: baseline;"><span style="color:#fff">Sovereign&nbsp;<span>Africa Ratings</span></a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{%url 'sar_home'%}">Home</a></li>
        
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->


  <section id="cover" class="min-vh-0">
    <div id="cover-caption">
        <div class="container">
            <div class="row text-white">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto mt-5 form p-4">
                    <h5 class="display-8 py-2 text-truncate">RSVP:&nbsp;{{event_instance}}</h5>
                    <p class="display-8 py-2 text-truncate"><strong>{{event_instance.event_date|date:"d/m/Y"}},{{event_instance.event_time|time:"H:i"}},&nbsp;{{event_instance.event_venue}}</strong></p>
                    <div class="col-md-12">
                        
                        <form class="justify-content-center lh-3" method="post" novalidate enctype="multipart/form-data" >
                          {% csrf_token %}
                  
                          <div class="form-group p-8">
                 
                            <div class="form-group col-md-12 mb-4">
                              {{ rsvp_form.title|as_crispy_field}}
                        
                          </div>
                              <div class="form-group col-md-12 mb-4">
                                  {{ rsvp_form.first_name|as_crispy_field}}
                              </div>
                              <div class="form-group col-md-12 mb-4">
                                  {{ rsvp_form.last_name|as_crispy_field}}
                              </div>

                              <div class="form-group col-md-12 mb-4">
                                {{ rsvp_form.company|as_crispy_field}}
                              </div>

                                <div class="form-group col-md-12 mb-4">
                                  {{ rsvp_form.contact_number|as_crispy_field}}
                              </div>
                                <div class="form-group col-md-12 mb-4">
                                  {{ rsvp_form.email_address|as_crispy_field}}
                              </div>
                              <div class="form-group col-md-12 mb-2">
                                {{ rsvp_form.confirm_attendance|as_crispy_field}}
                            </div> 

                              </div>
                  
                        
                          
                            
                          <div style="text-align: -webkit-center">
                            <button type="submit" class="btn btn-primary" style="background-color:#214a72;border-color:#214a72">Submit</button>
                            <a href="{%url 'eventsHomepage'%}"><button type="button" class="btn btn-danger">Cancel</button></a>
                             </div>
                        </form>
                  
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


  <!-- ======= Footer ======= -->
  <footer class="col-md-12">
    <div class="footer-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer-content">
              <div class="footer-head">
                <div class="footer-logo">
                 For more information, contact <strong>info@saratings.com</strong>
                </div>
                <div class="footer-icons" id="social_media_links">
                  <ul>
                    <li>
                      <a href="#"><i class="bi bi-twitter"></i></a>
                    </li>

                    </li>
                    <li>
                      <a href="#"><i class="bi bi-linkedin"></i></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- end single footer -->
         
        
         
        </div>
      </div>
    </div>
    <div class="footer-area-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="copyright text-center">
              <p>
                &copy; Copyright <strong>Sovereign Africa Ratings</strong>. All Rights Reserved
              </p>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js'%}"></script>

  <script>
    document.querySelector("#id_title").placeholder = "Mr, Mrs..."
  </script>

</body>

</html>

saratings/saratingsapp/templates/events/events_homepage_base_site_inheritance_not_used.html
{%extends 'layouts/base.html'%}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% block title %}
  <title>SAR|Home</title>
  {% endblock title %}
  <meta content="" name="description">
  <meta content="" name="keywords">
</head>

<body>


  <style>

  .single-well ul li{
    display: flex!important;
    font-size: 16px;
    font-family: "Open Sans", sans-serif;
    }

    #sar_profile{
      color:#3ec1d5;
      font-weight: bold;
      cursor:pointer;
      margin-bottom:0px!important;

    }
    .modal-dialog {
      margin-top: 20%;
    }

  #profile_image{
      height:245px;
      width:390px;
    }

    .single-team-member{
      border:none;
    }

    #sar_title{
      font-weight: bold;
      
    }

    #news,#testimonials,#insights,#research,#social_media_links,#articles{
      display:none;
    }
    .team-modal{
      cursor:pointer;
    }

    .footer-head h4 {
      padding-bottom:0px
  }

  </style>


  {%block landing_section%}
  <!-- ======= hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">
        <ol id="hero-carousel-indicators" class="carousel-indicators"></ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active" style="background-image: url(/static/assets/img/hero-carousel/1.jpg)">
            <div class="carousel-container" 
              style="display:block!important;
              top:110px!important;left:0px!important;right:0px!important">
              <div class="container">
            
                {% for event in get_all_events %}

                <div class="col-xxl-4 col-md-6">
                
                  <div class="card info-card sales-card" style="padding-bottom:0px!important;">
            
                    <div class="card-body pt-0">
                      <h5 class="card-title">
                        <a>
                          <span style="color:#012970!important;cursor:pointer;">
                            <!-- Default Accordion -->
                            </span></a><div class="accordion" id="voluntary"><a>
                                <div class="accordion-item" style="border:none">
                                  <h2 class="accordion-header" id="headingVoluntary">
                                    <button class="accordion-button collapsed" type="button" 
                                        data-bs-toggle="collapse" 
                                        data-bs-target="#collapseVoluntary" 
                                        aria-expanded="false" aria-controls="collapseVoluntary" 
                                        style="font-weight:bold;border-color:#242e4c;">
                                        {{event.event_title}}&nbsp;<i class="bi bi-info-circle" style="color:#dc3545"></i>
                                  </button>
                                  </h2>
                            
                                  <div id="collapseVoluntary" class="accordion-collapse collapse" data-bs-target="#collapseVoluntary" aria-expanded="false" aria-controls="collapseVoluntary" style="">
                                    <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;font-weight:bold">
                                      Agenda
                                     </div>
                                  <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                   {{event.agenda_item_1}}
                                  </div>
                                  <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_2}}
                                  </div>
                                  <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_3}}
                                  </div>
                                  <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_4}}
                                  </div> <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_5}}
                                  </div> <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_6}}
                                  </div> <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_7}}
                                  </div> <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_8}}
                                  </div> <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_9}}
                                  </div>
                                  <div class="accordion-body" style="font-size:16px!important;color:#242e4c!important;">
                                    {{event.agenda_item_10}}
                                  </div>
                                </div>
                              </div>
                           
                        </a>
                      </div></h5>
                    
                      <div class="align-items-center">
                        <div class="ps-0">
                          <a href="">
                            <p style="font-weight:600;font-size:1rem;color:#000000">{{event.introduction}}</p>
                          </a>
                          <span class="text ps-0 fw-bold" id="footer-text">
                            {{event.event_date|date:"d/m/Y"}},</span>
                            <span class="text pt-1 fw-bold" id="footer-text">
                           {{event.event_time|time:"H:i"}},</span>
                           <span class="text pt-1 fw-bold" id="footer-text">{{event.event_venue}}</span>
                        
                          <a href="{%url 'eventRSVP' event.event_id%}">
                          <span class="text fw-bold" style="color:#dc3545!important;float:right;cursor:pointer;">
                            RSVP
                          </span>
                          </a>
                        
                        </div>
                      </div>
                    </div>
            
                  </div>
                </div>
               
                  <!-- End card -->
                
                  {%endfor%}
          
     
        <!-- End card -->
              </div>
            </div>
          </div>

          
        </div>

      </div>
    </div>
  </section><!-- End Hero Section -->

  {%endblock landing_section%}

  {%block main_section%}
  {%endblock main_section%}

  {%block footer_main%}
  {%endblock footer_main%}

  {%block footer%}
  {%endblock footer%}
  
</body>

</html>